# Generated by Django 6.0.7 on 2026-07-25 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_paket', models.CharField(choices=[('Paket A', 'Paket A'), ('Paket B', 'Paket B'), ('Paket C', 'Paket C')], max_length=50)),
                ('tipe_kelas', models.CharField(choices=[('Reguler', 'Reguler'), ('Karyawan', 'Karyawan')], max_length=50)),
                ('registration_status', models.CharField(choices=[('DRAFT', 'Draft'), ('MENUNGGU_VERIFIKASI', 'Menunggu Verifikasi'), ('PERBAIKAN_DOKUMEN', 'Perbaikan Dokumen'), ('KLARIFIKASI_DATA', 'Klarifikasi Data'), ('DITERIMA', 'Diterima'), ('DITOLAK_PERMANEN', 'Ditolak Permanen')], default='MENUNGGU_VERIFIKASI', max_length=30)),
                ('biodata', models.JSONField(help_text='Menyimpan data pendaftaran lengkap (alamat, ortu, dll)')),
                ('dokumen', models.JSONField(help_text='Menyimpan path/nama file dokumen (foto, kk, ktp, ijazah)')),
                ('catatan_admin', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RejectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PERBAIKAN_DOKUMEN', 'Perbaikan Dokumen'), ('KLARIFIKASI_DATA', 'Klarifikasi Data'), ('DITOLAK_PERMANEN', 'Ditolak Permanen')], max_length=30)),
                ('reason', models.TextField()),
                ('rejected_fields', models.JSONField(blank=True, default=list, help_text="Daftar field yang bermasalah (e.g., ['kk', 'ijazah'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rejection_logs', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_logs', to='registration_api.studentregistration')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('NONE', 'Belum Ada Tagihan'), ('UNPAID', 'Belum Dibayar'), ('WAITING_CONFIRMATION', 'Menunggu Konfirmasi'), ('PAID', 'Lunas'), ('EXPIRED', 'Kedaluwarsa')], default='UNPAID', max_length=30)),
                ('metode_pembayaran', models.CharField(blank=True, max_length=50, null=True)),
                ('bukti_transfer', models.CharField(blank=True, help_text='Path bukti transfer yang diunggah', max_length=255, null=True)),
                ('expired_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='registration_api.studentregistration')),
            ],
        ),
    ]
