# Generated by Django 6.0.7 on 2026-07-26 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0002_academicyear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('nip', models.CharField(blank=True, max_length=50, null=True)),
                ('mapels', models.JSONField(blank=True, default=list)),
                ('kelas_list', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='Aktif', max_length=20)),
                ('rekening_type', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('DANA', 'DANA')], max_length=20, null=True)),
                ('rekening_nomor', models.CharField(blank=True, max_length=100, null=True)),
                ('rekening_nama', models.CharField(blank=True, max_length=150, null=True)),
                ('is_wali_kelas', models.BooleanField(default=False)),
                ('tanda_tangan', models.TextField(blank=True, null=True)),
                ('qr_tanda_tangan', models.TextField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
