# Generated by Django 6.0.7 on 2026-07-27 00:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('kode', models.CharField(blank=True, max_length=50, null=True)),
                ('paket', models.CharField(choices=[('Paket A', 'Paket A'), ('Paket B', 'Paket B'), ('Paket C', 'Paket C')], max_length=20)),
                ('status', models.CharField(default='Aktif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
