# Generated by Django 6.0.7 on 2026-07-27 01:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0005_matapelajaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('paket', models.CharField(choices=[('Paket A', 'Paket A'), ('Paket B', 'Paket B'), ('Paket C', 'Paket C')], max_length=20)),
                ('status', models.CharField(default='Aktif', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
