# Generated by Django 6.0.7 on 2026-07-27 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0006_fase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rombel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_rombel', models.CharField(max_length=150)),
                ('sistem_belajar', models.CharField(choices=[('Reguler', 'Reguler'), ('Karyawan', 'Karyawan')], max_length=20)),
                ('beban_belajar', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='Aktif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rombels', to='registration_api.fase')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rombels', to='registration_api.academicyear')),
                ('wali_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rombels_wali', to='registration_api.teacher')),
            ],
        ),
    ]
