# Generated by Django 6.0.7 on 2026-07-27 17:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0007_rombel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramBelajar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('paket', models.CharField(choices=[('Paket A', 'Paket A'), ('Paket B', 'Paket B'), ('Paket C', 'Paket C')], max_length=20)),
                ('jalur', models.CharField(choices=[('Reguler', 'Reguler'), ('Karyawan', 'Karyawan')], max_length=20)),
                ('target_total_skk', models.PositiveIntegerField(help_text='Jumlah total SKK yang harus dicapai siswa')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='Aktif', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['paket', 'jalur', 'nama'],
                'constraints': [models.UniqueConstraint(fields=('paket', 'jalur', 'nama'), name='unique_program_belajar')],
            },
        ),
    ]
