# Generated by Django 6.0.7 on 2026-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0008_programbelajar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matapelajaran',
            options={'ordering': ['paket', 'nama']},
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='bobot_skk',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='capaian_utama',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='cp_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='fase',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='is_wajib',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='kategori',
            field=models.CharField(default='Umum', max_length=50),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='kelas',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='kkm',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='semester',
            field=models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=10),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='sistem_belajar',
            field=models.CharField(choices=[('Reguler', 'Reguler'), ('Karyawan', 'Karyawan')], default='Reguler', max_length=20),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='tahun_ajaran',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='kode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='matapelajaran',
            constraint=models.UniqueConstraint(fields=('kode', 'paket', 'sistem_belajar'), name='unique_mapel_code_program'),
        ),
    ]
