# Generated by Django 6.0.7 on 2026-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0009_alter_matapelajaran_options_matapelajaran_bobot_skk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajaran',
            name='kode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
