# Generated by Django 6.0.7 on 2026-07-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0010_alter_matapelajaran_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='registration_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('MENUNGGU_VERIFIKASI', 'Menunggu Verifikasi'), ('PERBAIKAN_DOKUMEN', 'Perbaikan Dokumen'), ('KLARIFIKASI_DATA', 'Klarifikasi Data'), ('DITERIMA', 'Berkas Diterima / Menunggu Pembayaran'), ('MENUNGGU_PLOTTING_ROMBEL', 'Menunggu Plotting Rombel'), ('AKUN_AKTIF', 'Akun Aktif'), ('DITOLAK_PERMANEN', 'Ditolak Permanen')], default='MENUNGGU_VERIFIKASI', max_length=30),
        ),
    ]
