# Generated by Django 6.0.7 on 2026-07-27 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0011_alter_studentregistration_registration_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('gambar', models.TextField(blank=True, default='')),
                ('lampiran_pdf', models.TextField(blank=True, default='')),
                ('kategori', models.CharField(choices=[('PENGUMUMAN', 'Pengumuman'), ('PENTING', 'Penting'), ('INFO', 'Info')], default='PENGUMUMAN', max_length=20)),
                ('prioritas', models.CharField(choices=[('Tinggi', 'Tinggi'), ('Sedang', 'Sedang'), ('Rendah', 'Rendah')], default='Sedang', max_length=20)),
                ('target', models.CharField(choices=[('Semua', 'Semua'), ('Siswa', 'Siswa'), ('Guru', 'Guru')], default='Semua', max_length=20)),
                ('tanggal_publikasi', models.DateField()),
                ('tanggal_berakhir', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Draft', 'Draft'), ('Terjadwal', 'Terjadwal'), ('Nonaktif', 'Nonaktif')], default='Aktif', max_length=20)),
                ('created_role', models.CharField(default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal_publikasi', '-created_at'],
            },
        ),
    ]
