# Generated by Django 6.0.7 on 2026-07-27 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0012_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(blank=True, default='', max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('mata_pelajaran', models.CharField(blank=True, default='', max_length=150)),
                ('program', models.CharField(choices=[('SEMUA', 'Semua Program'), ('PAKET_A', 'Paket A'), ('PAKET_B', 'Paket B'), ('PAKET_C', 'Paket C')], default='SEMUA', max_length=20)),
                ('kelas', models.CharField(blank=True, default='Semua Kelas', max_length=150)),
                ('deskripsi', models.TextField(blank=True, default='')),
                ('cover_url', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('PDF', 'Upload PDF'), ('LINK', 'Link Ebook')], default='PDF', max_length=10)),
                ('file_url', models.TextField(blank=True, default='')),
                ('ebook_url', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Menunggu Persetujuan Admin'), ('PUBLISHED', 'Publik'), ('ARCHIVED', 'Arsip'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=20)),
                ('uploaded_role', models.CharField(default='ADMIN', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_books_approved', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_books_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buku Perpustakaan',
                'verbose_name_plural': 'Buku Perpustakaan',
                'ordering': ['-created_at'],
            },
        ),
    ]
