# Generated by Django 6.0.7 on 2026-07-28 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0013_librarybook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('IJAZAH', 'Ijazah'), ('SKL', 'SKL'), ('TRANSKRIP', 'Transkrip Nilai'), ('SERTIFIKAT', 'Sertifikat')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('graduation_year', models.CharField(blank=True, default='', max_length=20)),
                ('file_url', models.TextField()),
                ('verification_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Publish'), ('ARCHIVED', 'Arsip')], default='DRAFT', max_length=20)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_academic_documents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
