# Generated by Django 6.0.7 on 2026-07-28 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0014_academicdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=50)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('verification_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('subjects', models.JSONField(default=list)),
                ('kkm', models.DecimalField(decimal_places=2, default=75, max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('predicate', models.CharField(blank=True, max_length=50)),
                ('issue_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Publish'), ('REVOKED', 'Dicabut'), ('REPLACED', 'Diganti')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transcripts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_transcripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
