# Generated by Django 6.0.7 on 2026-07-28 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0015_academictranscript'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=50)),
                ('final_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('kkm', models.DecimalField(decimal_places=2, default=75, max_digits=5)),
                ('status', models.CharField(default='BELUM_TUNTAS', max_length=30)),
                ('teacher_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='registration_api.matapelajaran')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_student_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject__nama'],
                'unique_together': {('student', 'subject', 'academic_year', 'semester')},
            },
        ),
    ]
