# Generated by Django 6.0.7 on 2026-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0016_studentgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdocument',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicdocument',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='academicdocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Publish'), ('REVOKED', 'Dicabut'), ('ARCHIVED', 'Arsip')], default='DRAFT', max_length=20),
        ),
    ]
