# Generated by Django 6.0.7 on 2026-07-28 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0017_academicdocument_revoked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_type', models.CharField(choices=[('PENDAFTARAN', 'Pendaftaran'), ('SPP', 'SPP Bulanan')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UNPAID', 'Belum Dibayar'), ('WAITING_CONFIRMATION', 'Menunggu Verifikasi'), ('PAID', 'Lunas'), ('DECLINED', 'Ditolak'), ('EXPIRED', 'Kedaluwarsa')], default='UNPAID', max_length=30)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('payment_proof', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bills', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'bill_type', 'month', 'year'), name='unique_student_monthly_bill')],
            },
        ),
    ]
