# Generated by Django 6.0.7 on 2026-07-28 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0018_studentbill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_fee_reguler', models.DecimalField(decimal_places=2, default=100000, max_digits=12)),
                ('reg_fee_karyawan', models.DecimalField(decimal_places=2, default=150000, max_digits=12)),
                ('spp_reguler', models.DecimalField(decimal_places=2, default=20000, max_digits=12)),
                ('spp_karyawan', models.DecimalField(decimal_places=2, default=100000, max_digits=12)),
                ('discount_type_reguler', models.CharField(choices=[('NONE', 'Tanpa Keringanan'), ('DISCOUNT', 'Diskon Persen'), ('SCHOLARSHIP', 'Beasiswa')], default='NONE', max_length=20)),
                ('discount_value_reguler', models.PositiveSmallIntegerField(default=0)),
                ('discount_type_karyawan', models.CharField(choices=[('NONE', 'Tanpa Keringanan'), ('DISCOUNT', 'Diskon Persen'), ('SCHOLARSHIP', 'Beasiswa')], default='NONE', max_length=20)),
                ('discount_value_karyawan', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
