# Generated by Django 6.0.7 on 2026-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0019_paymentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsetting',
            name='spp_discount_type_karyawan',
            field=models.CharField(choices=[('NONE', 'Tanpa Keringanan'), ('DISCOUNT', 'Diskon Persen'), ('SCHOLARSHIP', 'Beasiswa')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsetting',
            name='spp_discount_type_reguler',
            field=models.CharField(choices=[('NONE', 'Tanpa Keringanan'), ('DISCOUNT', 'Diskon Persen'), ('SCHOLARSHIP', 'Beasiswa')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentsetting',
            name='spp_discount_value_karyawan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentsetting',
            name='spp_discount_value_reguler',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
