# Generated by Django 6.0.7 on 2026-07-28 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0020_paymentsetting_spp_discount_type_karyawan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('provider', models.CharField(choices=[('qris', 'QRIS'), ('bca', 'BCA'), ('mandiri', 'Mandiri'), ('bni', 'BNI'), ('gopay', 'GoPay'), ('ovo', 'OVO'), ('lainnya', 'Lainnya')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualPaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(blank=True, default='', max_length=100)),
                ('no_rekening', models.CharField(blank=True, default='', max_length=100)),
                ('pemilik_rekening', models.CharField(blank=True, default='', max_length=150)),
                ('qris_url', models.TextField(blank=True, default='')),
                ('instruksi', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_manual_payment_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
