# Generated by Django 6.0.7 on 2026-07-28 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0021_paymentmethodsetting_manualpaymentsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kompetensi', models.TextField()),
                ('bobot_skk', models.PositiveIntegerField(default=1)),
                ('semester', models.CharField(blank=True, default='', max_length=20)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='registration_api.matapelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('belum', 'Belum Tercapai'), ('proses', 'Dalam Proses'), ('tercapai', 'Tercapai')], default='belum', max_length=20)),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bukti', models.TextField(blank=True, default='')),
                ('catatan_guru', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='registration_api.competency')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration_api.studentgrade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_competencies', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_skk', to='registration_api.teacher')),
            ],
        ),
    ]
