# Generated by Django 6.0.7 on 2026-07-28 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0022_competency_studentcompetency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaianPembelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode_cp', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('fase', models.CharField(blank=True, default='', max_length=20)),
                ('tahun', models.CharField(default='2025', max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capaian_pembelajaran', to='registration_api.matapelajaran')),
            ],
        ),
        migrations.AddField(
            model_name='competency',
            name='cp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='registration_api.capaianpembelajaran'),
        ),
    ]
