# Generated by Django 6.0.7 on 2026-07-28 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0023_capaianpembelajaran_competency_cp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BebanBelajar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fase', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('target_skk', models.PositiveIntegerField(default=0)),
                ('tahun_berlaku', models.CharField(max_length=20)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_belajar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beban_belajar', to='registration_api.programbelajar')),
            ],
            options={
                'ordering': ['program_belajar', 'semester'],
                'constraints': [models.UniqueConstraint(fields=('program_belajar', 'fase', 'semester', 'tahun_berlaku'), name='unique_beban_belajar_program_semester')],
            },
        ),
    ]
