# Generated by Django 6.0.7 on 2026-07-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0025_chatconversation_chatparticipant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentitasLembaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pkbm', models.CharField(blank=True, default='', max_length=255)),
                ('nama_yayasan', models.CharField(blank=True, default='', max_length=255)),
                ('npsn', models.CharField(blank=True, default='', max_length=50)),
                ('nis', models.CharField(blank=True, default='', max_length=50)),
                ('alamat', models.TextField(blank=True, default='')),
                ('kecamatan', models.CharField(blank=True, default='', max_length=100)),
                ('kabupaten', models.CharField(blank=True, default='', max_length=100)),
                ('provinsi', models.CharField(blank=True, default='', max_length=100)),
                ('kode_pos', models.CharField(blank=True, default='', max_length=20)),
                ('nomor_telepon', models.CharField(blank=True, default='', max_length=50)),
                ('email_lembaga', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('logo_pkbm', models.TextField(blank=True, default='')),
                ('logo_yayasan', models.TextField(blank=True, default='')),
                ('qr_tanda_tangan_kepala_sekolah', models.TextField(blank=True, default='')),
                ('cap_stempel_digital', models.TextField(blank=True, default='')),
                ('tanda_tangan_kepala_sekolah', models.TextField(blank=True, default='')),
                ('nama_kepala_sekolah', models.CharField(blank=True, default='', max_length=255)),
                ('nip_kepala_sekolah', models.CharField(blank=True, default='', max_length=100)),
                ('nama_pejabat_ttd', models.CharField(blank=True, default='', max_length=255)),
                ('jabatan_pejabat_ttd', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Identitas Lembaga',
                'verbose_name_plural': 'Identitas Lembaga',
            },
        ),
    ]
