# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0026_identitaslembaga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identitaslembaga',
            old_name='cap_stempel_digital',
            new_name='atribut_pengesahan_digital',
        ),

        migrations.RenameField(
            model_name='identitaslembaga',
            old_name='nama_pejabat_ttd',
            new_name='nama_penandatangan',
        ),

        migrations.AddField(
            model_name='identitaslembaga',
            name='nomor_izin_operasional',
            field=models.CharField(
                max_length=255,
                blank=True,
                default='',
            ),
        ),

        migrations.RemoveField(
            model_name='identitaslembaga',
            name='jabatan_pejabat_ttd',
        ),

        migrations.RemoveField(
            model_name='identitaslembaga',
            name='nis',
        ),

        migrations.RemoveField(
            model_name='identitaslembaga',
            name='qr_tanda_tangan_kepala_sekolah',
        ),

        migrations.RemoveField(
            model_name='identitaslembaga',
            name='tanda_tangan_kepala_sekolah',
        ),
    ]
