# Generated by Django 6.0.7 on 2026-07-30 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0027_update_identitas_lembaga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLearningActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('OPEN_MATERI', 'Membuka Materi'), ('DOWNLOAD_MODUL', 'Mengunduh Modul'), ('UPLOAD_TUGAS', 'Mengumpulkan Tugas'), ('SELESAI_CBT', 'Menyelesaikan CBT')], max_length=30)),
                ('activity_date', models.DateField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity_type', 'activity_date'], name='registratio_activit_286a65_idx'), models.Index(fields=['student', 'activity_date'], name='registratio_student_259b03_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'activity_type', 'activity_date'), name='unique_student_daily_activity')],
            },
        ),
    ]
