# Generated by Django 6.0.7 on 2026-07-31 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0028_studentlearningactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriPembelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField(blank=True, default='')),
                ('nomor_pertemuan', models.PositiveIntegerField(default=1)),
                ('video_url', models.URLField(blank=True, default='')),
                ('file_modul', models.FileField(blank=True, null=True, upload_to='materi/modul/%Y/%m/')),
                ('file_lampiran', models.FileField(blank=True, null=True, upload_to='materi/lampiran/%Y/%m/')),
                ('tanggal_publikasi', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Dipublikasikan')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi_pembelajaran', to='registration_api.teacher')),
                ('kompetensi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materi_pembelajaran', to='registration_api.competency')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi_pembelajaran', to='registration_api.matapelajaran')),
                ('rombel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi_pembelajaran', to='registration_api.rombel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guru', 'status'], name='registratio_guru_id_ccdbed_idx'), models.Index(fields=['rombel', 'status'], name='registratio_rombel__4fd45d_idx'), models.Index(fields=['mata_pelajaran', 'status'], name='registratio_mata_pe_252ad7_idx')],
            },
        ),
    ]
