# Generated by Django 6.0.7 on 2026-07-31 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0030_tugaspembelajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugaspembelajaran',
            name='materi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_pembelajaran', to='registration_api.materipembelajaran'),
        ),
    ]
