# Generated by Django 6.0.7 on 2026-07-31 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0031_tugaspembelajaran_materi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSoalGuru',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('jenis_soal', models.CharField(choices=[('PILIHAN_GANDA', 'Pilihan Ganda'), ('ESAI', 'Esai')], max_length=20)),
                ('pertanyaan', models.TextField()),
                ('pilihan_jawaban', models.JSONField(blank=True, default=list)),
                ('jawaban_benar', models.TextField(blank=True, default='')),
                ('pembahasan', models.TextField(blank=True, default='')),
                ('tingkat_kesulitan', models.CharField(choices=[('MUDAH', 'Mudah'), ('SEDANG', 'Sedang'), ('SULIT', 'Sulit')], default='SEDANG', max_length=20)),
                ('bobot', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('NONAKTIF', 'Nonaktif')], default='AKTIF', max_length=20)),
                ('jumlah_digunakan', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_soal', to='registration_api.teacher')),
                ('kompetensi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_soal', to='registration_api.competency')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_soal', to='registration_api.matapelajaran')),
                ('materi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_soal', to='registration_api.materipembelajaran')),
                ('rombel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_soal', to='registration_api.rombel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guru', 'mata_pelajaran'], name='registratio_guru_id_a5fb65_idx'), models.Index(fields=['rombel', 'status'], name='registratio_rombel__840127_idx'), models.Index(fields=['jenis_soal'], name='registratio_jenis_s_8a383f_idx')],
            },
        ),
    ]
