# Generated by Django 6.0.7 on 2026-07-31 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0032_banksoalguru'),
    ]

    operations = [
        migrations.CreateModel(
            name='UjianCBTGuru',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_ujian', models.CharField(max_length=255)),
                ('jenis_ujian', models.CharField(choices=[('LATIHAN', 'Latihan'), ('ULANGAN_HARIAN', 'Ulangan Harian'), ('UTS', 'UTS'), ('REMEDIAL_UTS', 'Remedial UTS'), ('UAS', 'UAS'), ('REMEDIAL_UAS', 'Remedial UAS'), ('UJIAN_AKHIR', 'Ujian Akhir'), ('TRY_OUT', 'Try Out')], max_length=30)),
                ('durasi_menit', models.PositiveIntegerField(default=60)),
                ('nilai_minimum', models.PositiveIntegerField(default=70)),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_selesai', models.DateTimeField()),
                ('acak_soal', models.BooleanField(default=False)),
                ('acak_jawaban', models.BooleanField(default=False)),
                ('tampilkan_nilai', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('TERJADWAL', 'Terjadwal'), ('AKTIF', 'Aktif'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='TERJADWAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ujian_cbt', to='registration_api.teacher')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ujian_cbt', to='registration_api.matapelajaran')),
                ('rombel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ujian_cbt', to='registration_api.rombel')),
                ('soal', models.ManyToManyField(blank=True, related_name='ujian_cbt', to='registration_api.banksoalguru')),
            ],
            options={
                'ordering': ['-tanggal_mulai', '-created_at'],
                'indexes': [models.Index(fields=['guru', 'status'], name='registratio_guru_id_e15bf4_idx'), models.Index(fields=['rombel', 'tanggal_mulai'], name='registratio_rombel__b62039_idx'), models.Index(fields=['mata_pelajaran', 'jenis_ujian'], name='registratio_mata_pe_45f35a_idx')],
            },
        ),
    ]
