# Generated by Django 6.0.7 on 2026-08-01 03:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0033_ujiancbtguru'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengumpulanTugasSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jawaban_teks', models.TextField(blank=True, default='')),
                ('file_jawaban', models.FileField(blank=True, null=True, upload_to='tugas/jawaban/%Y/%m/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Sudah Dikumpulkan'), ('REVISION', 'Perlu Revisi'), ('GRADED', 'Sudah Dinilai')], default='SUBMITTED', max_length=20)),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback_guru', models.TextField(blank=True, default='')),
                ('dikumpulkan_pada', models.DateTimeField(auto_now_add=True)),
                ('dinilai_pada', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dinilai_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penilaian_tugas_diberikan', to=settings.AUTH_USER_MODEL)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumpulan_tugas', to=settings.AUTH_USER_MODEL)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumpulan_siswa', to='registration_api.tugaspembelajaran')),
            ],
            options={
                'ordering': ['-dikumpulkan_pada'],
                'indexes': [models.Index(fields=['tugas', 'status'], name='registratio_tugas_i_440a4e_idx'), models.Index(fields=['siswa', 'status'], name='registratio_siswa_i_5dcd4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tugas', 'siswa'), name='unique_pengumpulan_per_tugas_siswa')],
            },
        ),
    ]
