# Generated by Django 6.0.7 on 2026-08-01 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0034_pengumpulantugassiswa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaWajib',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_agenda', models.CharField(max_length=255)),
                ('jenis_agenda', models.CharField(choices=[('UTS', 'UTS'), ('UAS', 'UAS'), ('CBT_TERJADWAL', 'CBT Terjadwal'), ('TUTORIAL_TATAP_MUKA', 'Tutorial Tatap Muka'), ('PRAKTIK', 'Praktik'), ('PEMBINAAN', 'Pembinaan'), ('ZOOM_WAJIB', 'Zoom Wajib'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=30)),
                ('tanggal', models.DateField()),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField(blank=True, null=True)),
                ('lokasi_atau_link', models.CharField(blank=True, default='', max_length=500)),
                ('keterangan', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TERJADWAL', 'Terjadwal'), ('BERLANGSUNG', 'Berlangsung'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='TERJADWAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_wajib', to='registration_api.teacher')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_wajib', to='registration_api.matapelajaran')),
                ('rombel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_wajib', to='registration_api.rombel')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda_wajib', to='registration_api.academicyear')),
            ],
            options={
                'ordering': ['-tanggal', '-waktu_mulai'],
            },
        ),
        migrations.CreateModel(
            name='KehadiranAgenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('IZIN', 'Izin'), ('SAKIT', 'Sakit'), ('ALFA', 'Alfa')], default='ALFA', max_length=10)),
                ('catatan_guru', models.TextField(blank=True, default='')),
                ('dicatat_pada', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kehadiran', to='registration_api.agendawajib')),
                ('dicatat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kehadiran_agenda_dicatat', to=settings.AUTH_USER_MODEL)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kehadiran_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agenda', 'siswa__username'],
            },
        ),
        migrations.CreateModel(
            name='PengajuanIzinAgenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenis', models.CharField(choices=[('IZIN', 'Izin'), ('SAKIT', 'Sakit')], max_length=10)),
                ('alasan', models.TextField()),
                ('bukti', models.FileField(blank=True, null=True, upload_to='agenda_wajib/bukti_izin/')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Persetujuan'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='MENUNGGU', max_length=15)),
                ('catatan_verifikasi', models.TextField(blank=True, default='')),
                ('diverifikasi_pada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_izin', to='registration_api.agendawajib')),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengajuan_izin_diverifikasi', to=settings.AUTH_USER_MODEL)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_izin_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agendawajib',
            index=models.Index(fields=['guru', 'tanggal'], name='registratio_guru_id_540cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='agendawajib',
            index=models.Index(fields=['rombel', 'tanggal'], name='registratio_rombel__12b035_idx'),
        ),
        migrations.AddIndex(
            model_name='agendawajib',
            index=models.Index(fields=['tahun_ajaran', 'status'], name='registratio_tahun_a_5a6843_idx'),
        ),
        migrations.AddIndex(
            model_name='kehadiranagenda',
            index=models.Index(fields=['agenda', 'status'], name='registratio_agenda__0cf47f_idx'),
        ),
        migrations.AddIndex(
            model_name='kehadiranagenda',
            index=models.Index(fields=['siswa', 'status'], name='registratio_siswa_i_3cc709_idx'),
        ),
        migrations.AddConstraint(
            model_name='kehadiranagenda',
            constraint=models.UniqueConstraint(fields=('agenda', 'siswa'), name='unique_kehadiran_siswa_per_agenda'),
        ),
        migrations.AddIndex(
            model_name='pengajuanizinagenda',
            index=models.Index(fields=['agenda', 'status'], name='registratio_agenda__52e1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='pengajuanizinagenda',
            index=models.Index(fields=['siswa', 'status'], name='registratio_siswa_i_f1429b_idx'),
        ),
        migrations.AddConstraint(
            model_name='pengajuanizinagenda',
            constraint=models.UniqueConstraint(fields=('agenda', 'siswa'), name='unique_pengajuan_izin_siswa_per_agenda'),
        ),
    ]
