# Generated by Django 6.0.7 on 2026-08-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0035_agendawajib_kehadiranagenda_pengajuanizinagenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengumpulantugassiswa',
            name='link_video',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
