# Generated by Django 6.0.7 on 2026-08-01 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_api', '0036_pengumpulantugassiswa_link_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengerjaanUjianCBTSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SEDANG_MENGERJAKAN', 'Sedang Mengerjakan'), ('MENUNGGU_PENILAIAN', 'Menunggu Penilaian'), ('SELESAI', 'Selesai')], default='SEDANG_MENGERJAKAN', max_length=30)),
                ('mulai_pada', models.DateTimeField(auto_now_add=True)),
                ('selesai_pada', models.DateTimeField(blank=True, null=True)),
                ('nilai_otomatis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nilai_esai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nilai_akhir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('jumlah_benar', models.PositiveIntegerField(default=0)),
                ('jumlah_salah', models.PositiveIntegerField(default=0)),
                ('dinilai_pada', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dinilai_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penilaian_cbt_diberikan', to=settings.AUTH_USER_MODEL)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengerjaan_ujian_cbt', to=settings.AUTH_USER_MODEL)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengerjaan_siswa', to='registration_api.ujiancbtguru')),
            ],
            options={
                'ordering': ['-mulai_pada'],
            },
        ),
        migrations.CreateModel(
            name='JawabanUjianCBTSiswa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jawaban_pilihan', models.CharField(blank=True, default='', max_length=10)),
                ('jawaban_esai', models.TextField(blank=True, default='')),
                ('benar', models.BooleanField(blank=True, null=True)),
                ('skor_otomatis', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('skor_guru', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback_guru', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_siswa', to='registration_api.banksoalguru')),
                ('pengerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='registration_api.pengerjaanujiancbtsiswa')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pengerjaanujiancbtsiswa',
            index=models.Index(fields=['ujian', 'status'], name='registratio_ujian_i_701ead_idx'),
        ),
        migrations.AddIndex(
            model_name='pengerjaanujiancbtsiswa',
            index=models.Index(fields=['siswa', 'status'], name='registratio_siswa_i_b49ebc_idx'),
        ),
        migrations.AddConstraint(
            model_name='pengerjaanujiancbtsiswa',
            constraint=models.UniqueConstraint(fields=('ujian', 'siswa'), name='unique_pengerjaan_cbt_per_siswa'),
        ),
        migrations.AddIndex(
            model_name='jawabanujiancbtsiswa',
            index=models.Index(fields=['pengerjaan', 'soal'], name='registratio_pengerj_5c8385_idx'),
        ),
        migrations.AddConstraint(
            model_name='jawabanujiancbtsiswa',
            constraint=models.UniqueConstraint(fields=('pengerjaan', 'soal'), name='unique_jawaban_per_soal_cbt'),
        ),
    ]
